#ifndef UNITYCLOUDDOWNLOADERCORE_GLOBAL_H
#define UNITYCLOUDDOWNLOADERCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UNITYCLOUDDOWNLOADERCORE_LIBRARY)
#  define UCD_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define UCD_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UNITYCLOUDDOWNLOADERCORE_GLOBAL_H
